// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT07CadastrarCalculoNovoProcessoCPFValidoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT07CadastrarCalculoNovoProcessoCPFValido() {
    // Test name: CT07 CadastrarCalculoNovoProcessoCPFValido
    // Step # | name | target | value | comment
    // 1 | open | https://calculadora.dev.tecnologia.pgfn/calcsaj/list-repeticao-indebito |  | 
    driver.get("https://calculadora.dev.tecnologia.pgfn/calcsaj/list-repeticao-indebito");
    // 2 | setWindowSize | 1050x708 |  | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | click | css=.fa-navicon |  | 
    driver.findElement(By.cssSelector(".fa-navicon")).click();
    // 4 | click | id=lista_menu |  | 
    driver.findElement(By.id("lista_menu")).click();
    // 5 | click | id=n_processo_judicial |  | 
    driver.findElement(By.id("n_processo_judicial")).click();
    // 6 | type | id=n_processo_judicial | 00100.010020/2010-22 | 
    driver.findElement(By.id("n_processo_judicial")).sendKeys("00100.010020/2010-22");
    // 7 | click | css=.headerquebralinha |  | 
    driver.findElement(By.cssSelector(".headerquebralinha")).click();
    // 8 | select | css=.headerquebralinha | label=Judicial | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".headerquebralinha"));
      dropdown.findElement(By.xpath("//option[. = 'Judicial']")).click();
    }
    // 9 | click | css=.headerquebralinha |  | 
    driver.findElement(By.cssSelector(".headerquebralinha")).click();
    // 10 | click | id=juizo |  | 
    driver.findElement(By.id("juizo")).click();
    // 11 | type | id=juizo | testes juizo | 
    driver.findElement(By.id("juizo")).sendKeys("testes juizo");
    // 12 | click | id=tipo_juizo |  | 
    driver.findElement(By.id("tipo_juizo")).click();
    // 13 | type | id=tipo_juizo | tipo juizo testes | 
    driver.findElement(By.id("tipo_juizo")).sendKeys("tipo juizo testes");
    // 14 | click | css=input:nth-child(1) |  | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 15 | click | css=#a9b9306321f8-5 > .ng-option-label |  | 
    driver.findElement(By.cssSelector("#a9b9306321f8-5 > .ng-option-label")).click();
    // 16 | click | css=.custom-select |  | 
    driver.findElement(By.cssSelector(".custom-select")).click();
    // 17 | select | css=.custom-select | label=Apelação | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".custom-select"));
      dropdown.findElement(By.xpath("//option[. = 'Apelação']")).click();
    }
    // 18 | click | css=.custom-select |  | 
    driver.findElement(By.cssSelector(".custom-select")).click();
    // 19 | click | id=cpf_cnpj_parte |  | 
    driver.findElement(By.id("cpf_cnpj_parte")).click();
    // 20 | type | id=cpf_cnpj_parte | 524.047.731-00 | 
    driver.findElement(By.id("cpf_cnpj_parte")).sendKeys("524.047.731-00");
    // 21 | click | id=nome_parte |  | 
    driver.findElement(By.id("nome_parte")).click();
    // 22 | type | id=nome_parte | Teste1 | 
    driver.findElement(By.id("nome_parte")).sendKeys("Teste1");
    // 23 | click | css=.marginbutton:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".marginbutton:nth-child(2)")).click();
  }
}
