// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT08CadastrarNovoCalculoProcessoExistenteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT08CadastrarNovoCalculoProcessoExistente() {
    // Test name: CT08 CadastrarNovoCalculoProcessoExistente
    // Step # | name | target | value | comment
    // 1 | open | https://vmrhel7sisgest.teste.tecnologia.pgfn/cas/login?service=https%3A%2F%2Fcalculadora.dev.tecnologia.pgfn%2Fcalcsaj%2F%23%2Fvalida-login++++++ |  | 
    driver.get("https://vmrhel7sisgest.teste.tecnologia.pgfn/cas/login?service=https%3A%2F%2Fcalculadora.dev.tecnologia.pgfn%2Fcalcsaj%2F%23%2Fvalida-login++++++");
    // 2 | setWindowSize | 1382x744 |  | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | click | css=.fa-navicon |  | 
    driver.findElement(By.cssSelector(".fa-navicon")).click();
    // 4 | click | id=lista_menu |  | 
    driver.findElement(By.id("lista_menu")).click();
    // 5 | click | id=n_processo_judicial |  | 
    driver.findElement(By.id("n_processo_judicial")).click();
    // 6 | type | id=n_processo_judicial | 00000.000000/0000-00 | 
    driver.findElement(By.id("n_processo_judicial")).sendKeys("00000.000000/0000-00");
    // 7 | click | css=.headerquebralinha |  | 
    driver.findElement(By.cssSelector(".headerquebralinha")).click();
    // 8 | click | css=.marg-edit |  | 
    driver.findElement(By.cssSelector(".marg-edit")).click();
    // 9 | click | id=cpf_cnpj_interessado |  | 
    driver.findElement(By.id("cpf_cnpj_interessado")).click();
    // 10 | type | id=cpf_cnpj_interessado | 019.763.821-06 | 
    driver.findElement(By.id("cpf_cnpj_interessado")).sendKeys("019.763.821-06");
    // 11 | type | id=nome_interessado | testes | 
    driver.findElement(By.id("nome_interessado")).sendKeys("testes");
    // 12 | click | css=.col-md-2 > .custom-select |  | 
    driver.findElement(By.cssSelector(".col-md-2 > .custom-select")).click();
    // 13 | select | css=.col-md-2 > .custom-select | label=Janeiro | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".col-md-2 > .custom-select"));
      dropdown.findElement(By.xpath("//option[. = 'Janeiro']")).click();
    }
    // 14 | click | css=.col-md-2 > .custom-select |  | 
    driver.findElement(By.cssSelector(".col-md-2 > .custom-select")).click();
    // 15 | click | id=ano |  | 
    driver.findElement(By.id("ano")).click();
    // 16 | type | id=ano | 1998 | 
    driver.findElement(By.id("ano")).sendKeys("1998");
    // 17 | click | id=valor_uniatrio |  | 
    driver.findElement(By.id("valor_uniatrio")).click();
    // 18 | click | css=.col-md-2:nth-child(1) > .form-control |  | 
    driver.findElement(By.cssSelector(".col-md-2:nth-child(1) > .form-control")).click();
    // 19 | type | css=.col-md-2:nth-child(1) > .form-control | 02/02/2020 | 
    driver.findElement(By.cssSelector(".col-md-2:nth-child(1) > .form-control")).sendKeys("02/02/2020");
    // 20 | click | css=#mat-tab-content-1-1 > .mat-tab-body-content |  | 
    driver.findElement(By.cssSelector("#mat-tab-content-1-1 > .mat-tab-body-content")).click();
    // 21 | click | css=.col-md-1:nth-child(5) > .btn |  | 
    driver.findElement(By.cssSelector(".col-md-1:nth-child(5) > .btn")).click();
    // 22 | click | css=.btn:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
  }
}
