// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT09CadastrarNovoCalculoNovoProcessoCPFInvlidoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT09CadastrarNovoCalculoNovoProcessoCPFInvlido() {
    // Test name: CT09 CadastrarNovoCalculoNovoProcessoCPFInválido
    // Step # | name | target | value | comment
    // 1 | open | https://vmrhel7sisgest.teste.tecnologia.pgfn/cas/login?service=https%3A%2F%2Fcalculadora.dev.tecnologia.pgfn%2Fcalcsaj%2F%23%2Fvalida-login++++++ |  | 
    driver.get("https://vmrhel7sisgest.teste.tecnologia.pgfn/cas/login?service=https%3A%2F%2Fcalculadora.dev.tecnologia.pgfn%2Fcalcsaj%2F%23%2Fvalida-login++++++");
    // 2 | setWindowSize | 1366x728 |  | 
    driver.manage().window().setSize(new Dimension(1366, 728));
    // 3 | click | css=.fa-navicon |  | 
    driver.findElement(By.cssSelector(".fa-navicon")).click();
    // 4 | click | id=lista_menu |  | 
    driver.findElement(By.id("lista_menu")).click();
    // 5 | click | id=n_processo_judicial |  | 
    driver.findElement(By.id("n_processo_judicial")).click();
    // 6 | type | id=n_processo_judicial | 01010.022003/2556-65 | 
    driver.findElement(By.id("n_processo_judicial")).sendKeys("01010.022003/2556-65");
    // 7 | click | css=.headerquebralinha |  | 
    driver.findElement(By.cssSelector(".headerquebralinha")).click();
    // 8 | select | css=.headerquebralinha | label=Judicial | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".headerquebralinha"));
      dropdown.findElement(By.xpath("//option[. = 'Judicial']")).click();
    }
    // 9 | click | css=.headerquebralinha |  | 
    driver.findElement(By.cssSelector(".headerquebralinha")).click();
    // 10 | type | id=juizo | testes juizo | 
    driver.findElement(By.id("juizo")).sendKeys("testes juizo");
    // 11 | click | id=tipo_juizo |  | 
    driver.findElement(By.id("tipo_juizo")).click();
    // 12 | type | id=tipo_juizo | tipo juizo testes | 
    driver.findElement(By.id("tipo_juizo")).sendKeys("tipo juizo testes");
    // 13 | type | id=tipo_juizo | tipo juizo testes | 
    driver.findElement(By.id("tipo_juizo")).sendKeys("tipo juizo testes");
    // 14 | sendKeys | css=input:nth-child(1) | ${KEY_ENTER} | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).sendKeys(Keys.ENTER);
    // 15 | select | css=.custom-select | label=Adjudicação | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".custom-select"));
      dropdown.findElement(By.xpath("//option[. = 'Adjudicação']")).click();
    }
    // 16 | click | id=cpf_cnpj_parte |  | 
    driver.findElement(By.id("cpf_cnpj_parte")).click();
    // 17 | type | id=cpf_cnpj_parte | 058.021.531-80 | 
    driver.findElement(By.id("cpf_cnpj_parte")).sendKeys("058.021.531-80");
    // 18 | click | id=nome_parte |  | 
    driver.findElement(By.id("nome_parte")).click();
    // 19 | type | id=nome_parte | Teste1 | 
    driver.findElement(By.id("nome_parte")).sendKeys("Teste1");
    // 20 | click | css=.marg-edit |  | 
    driver.findElement(By.cssSelector(".marg-edit")).click();
    // 21 | click | id=cpf_cnpj_interessado |  | 
    driver.findElement(By.id("cpf_cnpj_interessado")).click();
    // 22 | type | id=cpf_cnpj_interessado | 058.021.351-80 | 
    driver.findElement(By.id("cpf_cnpj_interessado")).sendKeys("058.021.351-80");
    // 23 | click | id=nome_interessado |  | 
    driver.findElement(By.id("nome_interessado")).click();
    // 24 | type | id=nome_interessado | testes | 
    driver.findElement(By.id("nome_interessado")).sendKeys("testes");
  }
}
