// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT10CadastrarNovoCalculoNovoProcessoCPFValidoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT10CadastrarNovoCalculoNovoProcessoCPFValido() {
    // Test name: CT10 CadastrarNovoCalculoNovoProcessoCPFValido
    // Step # | name | target | value | comment
    // 1 | open | https://vmrhel7sisgest.teste.tecnologia.pgfn/cas/login?service=https%3A%2F%2Fcalculadora.dev.tecnologia.pgfn%2Fcalcsaj%2F%23%2Fvalida-login++++++ |  | 
    driver.get("https://vmrhel7sisgest.teste.tecnologia.pgfn/cas/login?service=https%3A%2F%2Fcalculadora.dev.tecnologia.pgfn%2Fcalcsaj%2F%23%2Fvalida-login++++++");
    // 2 | setWindowSize | 1366x728 |  | 
    driver.manage().window().setSize(new Dimension(1366, 728));
    // 3 | click | css=.fa-navicon |  | 
    driver.findElement(By.cssSelector(".fa-navicon")).click();
    // 4 | click | id=lista_menu |  | 
    driver.findElement(By.id("lista_menu")).click();
    // 5 | click | id=n_processo_judicial |  | 
    driver.findElement(By.id("n_processo_judicial")).click();
    // 6 | type | id=n_processo_judicial | 01010.222333/6656-54 | 
    driver.findElement(By.id("n_processo_judicial")).sendKeys("01010.222333/6656-54");
    // 7 | click | css=.headerquebralinha |  | 
    driver.findElement(By.cssSelector(".headerquebralinha")).click();
    // 8 | select | css=.headerquebralinha | label=Judicial | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".headerquebralinha"));
      dropdown.findElement(By.xpath("//option[. = 'Judicial']")).click();
    }
    // 9 | click | css=.headerquebralinha |  | 
    driver.findElement(By.cssSelector(".headerquebralinha")).click();
    // 10 | click | id=juizo |  | 
    driver.findElement(By.id("juizo")).click();
    // 11 | type | id=juizo | testes juizo | 
    driver.findElement(By.id("juizo")).sendKeys("testes juizo");
    // 12 | click | css=.body_content |  | 
    driver.findElement(By.cssSelector(".body_content")).click();
    // 13 | click | id=tipo_juizo |  | 
    driver.findElement(By.id("tipo_juizo")).click();
    // 14 | type | id=tipo_juizo | tipo juizo testes | 
    driver.findElement(By.id("tipo_juizo")).sendKeys("tipo juizo testes");
    // 15 | click | css=input:nth-child(1) |  | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 16 | click | xpath=//span[contains(.,'CAF - Coordenação-Geral de Assuntos Financeiros')] |  | 
    driver.findElement(By.xpath("//span[contains(.,\'CAF - Coordenação-Geral de Assuntos Financeiros\')]")).click();
    // 17 | click | css=.custom-select |  | 
    driver.findElement(By.cssSelector(".custom-select")).click();
    // 18 | select | css=.custom-select | label=Argüição de Descumprimento de Preceto Fundamental | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".custom-select"));
      dropdown.findElement(By.xpath("//option[. = 'Argüição de Descumprimento de Preceto Fundamental']")).click();
    }
    // 19 | click | id=cpf_cnpj_parte |  | 
    driver.findElement(By.id("cpf_cnpj_parte")).click();
    // 20 | type | id=cpf_cnpj_parte | 058.021.531-80 | 
    driver.findElement(By.id("cpf_cnpj_parte")).sendKeys("058.021.531-80");
    // 21 | click | id=nome_parte |  | 
    driver.findElement(By.id("nome_parte")).click();
    // 22 | type | id=nome_parte | Teste1 | 
    driver.findElement(By.id("nome_parte")).sendKeys("Teste1");
    // 23 | click | css=.marg-edit |  | 
    driver.findElement(By.cssSelector(".marg-edit")).click();
    // 24 | click | id=cpf_cnpj_interessado |  | 
    driver.findElement(By.id("cpf_cnpj_interessado")).click();
    // 25 | type | id=cpf_cnpj_interessado | 019.763.821-06 | 
    driver.findElement(By.id("cpf_cnpj_interessado")).sendKeys("019.763.821-06");
    // 26 | click | id=nome_interessado |  | 
    driver.findElement(By.id("nome_interessado")).click();
    // 27 | type | id=nome_interessado | testes interessado | 
    driver.findElement(By.id("nome_interessado")).sendKeys("testes interessado");
    // 28 | click | css=.col-md-11 > .form-control |  | 
    driver.findElement(By.cssSelector(".col-md-11 > .form-control")).click();
    // 29 | type | css=.ng-valid:nth-child(3) | Observação | 
    driver.findElement(By.cssSelector(".ng-valid:nth-child(3)")).sendKeys("Observação");
    // 30 | click | css=#mat-tab-content-1-1 > .mat-tab-body-content |  | 
    driver.findElement(By.cssSelector("#mat-tab-content-1-1 > .mat-tab-body-content")).click();
    // 31 | click | css=.col-md-2 > .custom-select |  | 
    driver.findElement(By.cssSelector(".col-md-2 > .custom-select")).click();
    // 32 | select | css=.col-md-2 > .custom-select | label=Abril | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".col-md-2 > .custom-select"));
      dropdown.findElement(By.xpath("//option[. = 'Abril']")).click();
    }
    // 33 | click | css=.col-md-2 > .custom-select |  | 
    driver.findElement(By.cssSelector(".col-md-2 > .custom-select")).click();
    // 34 | click | id=ano |  | 
    driver.findElement(By.id("ano")).click();
    // 35 | type | id=ano | 1998 | 
    driver.findElement(By.id("ano")).sendKeys("1998");
    // 36 | click | id=valor_uniatrio |  | 
    driver.findElement(By.id("valor_uniatrio")).click();
    // 37 | assertAlert | Erro nos indices SELIC! |  | 
    assertThat(driver.switchTo().alert().getText(), is("Erro nos indices SELIC!"));
    // 38 | click | css=.btn:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 39 | click | css=.marginbutton:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".marginbutton:nth-child(2)")).click();
    // 40 | runScript | window.scrollTo(0,0) |  | 
    js.executeScript("window.scrollTo(0,0)");
  }
}
