// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT01PrecredenciamentoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT01Precredenciamento() {
    // Test name: CT01Precredenciamento
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://10.1.203.185/");
    // 2 | setWindowSize | 1050x708 |  | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | click | css=#sexo |  | 
    driver.findElement(By.cssSelector("#sexo")).click();
    // 4 | select | id=sexo | label=FEMININO | 
    {
      WebElement dropdown = driver.findElement(By.id("sexo"));
      dropdown.findElement(By.xpath("//option[. = 'FEMININO']")).click();
    }
    // 5 | click | id=sexo |  | 
    driver.findElement(By.id("sexo")).click();
    // 6 | click | id=nome-social |  | 
    driver.findElement(By.id("nome-social")).click();
    // 7 | click | css=.row:nth-child(4) > .col-md-4:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".row:nth-child(4) > .col-md-4:nth-child(2)")).click();
    // 8 | click | id=data-nascimento |  | 
    driver.findElement(By.id("data-nascimento")).click();
    // 9 | type | id=data-nascimento | 0001-07-01 | 
    driver.findElement(By.id("data-nascimento")).sendKeys("0001-07-01");
    // 10 | type | id=data-nascimento | 0019-07-01 | 
    driver.findElement(By.id("data-nascimento")).sendKeys("0019-07-01");
    // 11 | type | id=data-nascimento | 0199-07-01 | 
    driver.findElement(By.id("data-nascimento")).sendKeys("0199-07-01");
    // 12 | type | id=data-nascimento | 1998-07-01 | 
    driver.findElement(By.id("data-nascimento")).sendKeys("1998-07-01");
    // 13 | click | id=estado-civil |  | 
    driver.findElement(By.id("estado-civil")).click();
    // 14 | select | id=estado-civil | label=SOLTEIRO | 
    {
      WebElement dropdown = driver.findElement(By.id("estado-civil"));
      dropdown.findElement(By.xpath("//option[. = 'SOLTEIRO']")).click();
    }
    // 15 | click | id=estado-civil |  | 
    driver.findElement(By.id("estado-civil")).click();
    // 16 | click | id=grau-instrucao |  | 
    driver.findElement(By.id("grau-instrucao")).click();
    // 17 | select | id=grau-instrucao | label=SUPERIOR INCOMPLETO | 
    {
      WebElement dropdown = driver.findElement(By.id("grau-instrucao"));
      dropdown.findElement(By.xpath("//option[. = 'SUPERIOR INCOMPLETO']")).click();
    }
    // 18 | click | id=grau-instrucao |  | 
    driver.findElement(By.id("grau-instrucao")).click();
    // 19 | click | id=rg |  | 
    driver.findElement(By.id("rg")).click();
    // 20 | type | id=rg | 3505273 | 
    driver.findElement(By.id("rg")).sendKeys("3505273");
    // 21 | click | id=orgao-emissor-rg |  | 
    driver.findElement(By.id("orgao-emissor-rg")).click();
    // 22 | type | id=orgao-emissor-rg | SSPDF | 
    driver.findElement(By.id("orgao-emissor-rg")).sendKeys("SSPDF");
    // 23 | type | id=naturalidade | BRASILEIRA | 
    driver.findElement(By.id("naturalidade")).sendKeys("BRASILEIRA");
    // 24 | type | id=nacionalidade | BRASILEIRA | 
    driver.findElement(By.id("nacionalidade")).sendKeys("BRASILEIRA");
    // 25 | click | id=profissao |  | 
    driver.findElement(By.id("profissao")).click();
    // 26 | type | id=profissao | ESTUDANTE | 
    driver.findElement(By.id("profissao")).sendKeys("ESTUDANTE");
    // 27 | click | id=nome-pai |  | 
    driver.findElement(By.id("nome-pai")).click();
    // 28 | type | id=nome-pai | JOSUÉ  | 
    driver.findElement(By.id("nome-pai")).sendKeys("JOSUÉ ");
    // 29 | type | id=nome-mae | RENATA | 
    driver.findElement(By.id("nome-mae")).sendKeys("RENATA");
    // 30 | type | id=telefone-celular | (61)99122-4517 | 
    driver.findElement(By.id("telefone-celular")).sendKeys("(61)99122-4517");
    // 31 | type | id=telefone-residencial | (61)32646-612 | 
    driver.findElement(By.id("telefone-residencial")).sendKeys("(61)32646-612");
    // 32 | type | id=telefone-comercial | (61)99122-4517 | 
    driver.findElement(By.id("telefone-comercial")).sendKeys("(61)99122-4517");
    // 33 | click | css=.ng-wizard-btn-next |  | 
    driver.findElement(By.cssSelector(".ng-wizard-btn-next")).click();
    // 34 | click | id=cep |  | 
    driver.findElement(By.id("cep")).click();
    // 35 | type | id=cep | 73251-903 | 
    driver.findElement(By.id("cep")).sendKeys("73251-903");
    // 36 | click | id=habitacao |  | 
    driver.findElement(By.id("habitacao")).click();
    // 37 | select | id=habitacao | label=PRÓPRIA | 
    {
      WebElement dropdown = driver.findElement(By.id("habitacao"));
      dropdown.findElement(By.xpath("//option[. = 'PRÓPRIA']")).click();
    }
    // 38 | click | id=habitacao |  | 
    driver.findElement(By.id("habitacao")).click();
    // 39 | click | css=.ng-wizard-btn-next |  | 
    driver.findElement(By.cssSelector(".ng-wizard-btn-next")).click();
    // 40 | click | id=dt-admissao |  | 
    driver.findElement(By.id("dt-admissao")).click();
  }
}
