// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT01CalSAJTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT01CalSAJ() {
    // Test name: CT01 CalSAJ
    // Step # | name | target | value | comment
    // 1 | open | https://calculadora.dev.tecnologia.pgfn/calcsaj/list-repeticao-indebito |  | 
    driver.get("https://calculadora.dev.tecnologia.pgfn/calcsaj/list-repeticao-indebito");
    // 2 | setWindowSize | 1050x708 |  | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | click | css=.fa-navicon |  | 
    driver.findElement(By.cssSelector(".fa-navicon")).click();
    // 4 | click | css=.navbar-toggle |  | 
    driver.findElement(By.cssSelector(".navbar-toggle")).click();
    // 5 | click | css=.mat-row:nth-child(1) .btn-outline-success |  | 
    driver.findElement(By.cssSelector(".mat-row:nth-child(1) .btn-outline-success")).click();
    // 6 | click | css=.marg-edit |  | 
    driver.findElement(By.cssSelector(".marg-edit")).click();
    // 7 | click | id=cpf_cnpj_interessado |  | 
    driver.findElement(By.id("cpf_cnpj_interessado")).click();
    // 8 | type | id=cpf_cnpj_interessado | 01.976.382/1061-23 | 
    driver.findElement(By.id("cpf_cnpj_interessado")).sendKeys("01.976.382/1061-23");
    // 9 | click | id=nome_interessado |  | 
    driver.findElement(By.id("nome_interessado")).click();
    // 10 | type | id=nome_interessado | testes interessado | 
    driver.findElement(By.id("nome_interessado")).sendKeys("testes interessado");
    // 11 | click | css=.col-md-2:nth-child(1) > .form-control |  | 
    driver.findElement(By.cssSelector(".col-md-2:nth-child(1) > .form-control")).click();
    // 12 | click | css=.is-highlighted |  | 
    driver.findElement(By.cssSelector(".is-highlighted")).click();
    // 13 | click | css=.col-md-2 > .custom-select |  | 
    driver.findElement(By.cssSelector(".col-md-2 > .custom-select")).click();
    // 14 | select | css=.col-md-2 > .custom-select | label=Julho | 
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".col-md-2 > .custom-select"));
      dropdown.findElement(By.xpath("//option[. = 'Julho']")).click();
    }
    // 15 | click | css=.col-md-2 > .custom-select |  | 
    driver.findElement(By.cssSelector(".col-md-2 > .custom-select")).click();
    // 16 | click | id=ano |  | 
    driver.findElement(By.id("ano")).click();
    // 17 | type | id=ano | 1998 | 
    driver.findElement(By.id("ano")).sendKeys("1998");
    // 18 | click | id=valor_uniatrio |  | 
    driver.findElement(By.id("valor_uniatrio")).click();
    // 19 | assertAlert | Erro nos indices SELIC! |  | 
    assertThat(driver.switchTo().alert().getText(), is("Erro nos indices SELIC!"));
    // 20 | click | css=.btn:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 21 | assertAlert | CPF/CNJP Interessado inválido! |  | 
    assertThat(driver.switchTo().alert().getText(), is("CPF/CNJP Interessado inválido!"));
    // 22 | click | id=cpf_cnpj_interessado |  | 
    driver.findElement(By.id("cpf_cnpj_interessado")).click();
    // 23 | type | id=cpf_cnpj_interessado | 058.021.351-80 | 
    driver.findElement(By.id("cpf_cnpj_interessado")).sendKeys("058.021.351-80");
    // 24 | assertAlert | Erro nos indices SELIC! |  | 
    assertThat(driver.switchTo().alert().getText(), is("Erro nos indices SELIC!"));
    // 25 | click | css=.btn:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 26 | assertAlert | CPF/CNJP Interessado inválido! |  | 
    assertThat(driver.switchTo().alert().getText(), is("CPF/CNJP Interessado inválido!"));
    // 27 | click | css=.btn:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    // 28 | assertAlert | CPF/CNJP Interessado inválido! |  | 
    assertThat(driver.switchTo().alert().getText(), is("CPF/CNJP Interessado inválido!"));
    // 29 | click | css=.btn-secondary |  | 
    driver.findElement(By.cssSelector(".btn-secondary")).click();
    // 30 | runScript | window.scrollTo(0,0) |  | 
    js.executeScript("window.scrollTo(0,0)");
    // 31 | click | css=.mat-row:nth-child(10) .btn:nth-child(1) > .fa |  | 
    driver.findElement(By.cssSelector(".mat-row:nth-child(10) .btn:nth-child(1) > .fa")).click();
    // 32 | mouseDownAt | css=.modal | 1339,376 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 33 | mouseMoveAt | css=.modal | 1339,376 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 34 | mouseUpAt | css=.modal | 1339,376 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 35 | click | css=.fa-file |  | 
    driver.findElement(By.cssSelector(".fa-file")).click();
    // 36 | mouseDownAt | css=.modal:nth-child(12) | 1349,575 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal:nth-child(12)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 37 | mouseMoveAt | css=.modal:nth-child(12) | 1349,575 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal:nth-child(12)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 38 | mouseUpAt | css=.modal:nth-child(12) | 1349,575 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal:nth-child(12)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 39 | click | css=.btn-primary:nth-child(2) |  | 
    driver.findElement(By.cssSelector(".btn-primary:nth-child(2)")).click();
    // 40 | mouseDownAt | css=.modal:nth-child(12) | 1350,495 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal:nth-child(12)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 41 | mouseMoveAt | css=.modal:nth-child(12) | 1350,495 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal:nth-child(12)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 42 | mouseUpAt | css=.modal:nth-child(12) | 1350,495 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".modal:nth-child(12)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
  }
}
