// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CT01LoginCorretoCalcSAJTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cT01LoginCorretoCalcSAJ() {
    // Test name: CT01 LoginCorretoCalcSAJ
    // Step # | name | target | value | comment
    // 1 | open | https://vmrhel7sisgest.teste.tecnologia.pgfn/cas/login?service=https%3A%2F%2Fcalculadora.dev.tecnologia.pgfn%2Fcalcsaj%2F%23%2Fvalida-login++++++ |  | 
    driver.get("https://vmrhel7sisgest.teste.tecnologia.pgfn/cas/login?service=https%3A%2F%2Fcalculadora.dev.tecnologia.pgfn%2Fcalcsaj%2F%23%2Fvalida-login++++++");
    // 2 | setWindowSize | 1050x708 |  | 
    driver.manage().window().setSize(new Dimension(1050, 708));
    // 3 | click | id=username |  | 
    driver.findElement(By.id("username")).click();
    // 4 | click | id=password |  | 
    driver.findElement(By.id("password")).click();
    // 5 | type | id=password | 123456 | 
    driver.findElement(By.id("password")).sendKeys("123456");
    // 6 | click | name=submit |  | 
    driver.findElement(By.name("submit")).click();
  }
}
